version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"             # Location of the `pom.xml` file in your project
    schedule:
      interval: "daily"        # Check for updates daily
#    groups:
#      npm:
#        patterns:
#          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"