name: Dependabot auto-merges
on:
  pull_request_target:
    types:
    - opened
    - reopened
    - synchronize

permissions:
  contents: write
  pull-requests: write

jobs:
  check_context:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout with ref ${{ github.sha }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: watch previous run
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: github.run_number > 1
        shell: bash
        run: |
          workflow_name="Dependabot auto-merges"
          # Get current run number
          current_run_number=${{ github.run_number }}
        
          # Search for earlier in-progress run of this workflow
          previous_run_in_progress=$(gh run list --workflow "${workflow_name}" --limit 10 --json databaseId,number,status --jq \
          ".[] | select(.number < $current_run_number and .status == \"in_progress\") | .databaseId" | head -n 1)
          
          if [ -z "$previous_run_in_progress" ]; then
            echo "✅ No previous in-progress run found. Continuing."
          else
            max_wait=30  # 5 minutes
            waited=0
            
            while true; do
              status=$(gh run view "$previous_run_in_progress" --json status --jq '.status')
              if [[ "$status" == "completed" ]]; then
                echo "✅ Previous run completed."
                break
              fi
              echo "⏳ Still waiting on run $previous_run_in_progress..."
              sleep 10
              waited=$((waited + 10))
              if [ "$waited" -ge "$max_wait" ]; then
                echo "❌ Timeout waiting on previous run."
                exit 1
              fi
            done
          fi


  fetch_metadata:
    runs-on: ubuntu-latest
    needs:
      - check_context
    if: github.actor == 'dependabot[bot]'
    outputs:
      package-ecosystem: ${{ steps.metadata.outputs.package-ecosystem }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

  automerge_npm_pull_request:
    runs-on: ubuntu-latest
    needs:
      - fetch_metadata
    if: ${{ github.actor == 'dependabot[bot]' && needs.fetch_metadata.outputs.package-ecosystem == 'npm_and_yarn' }}
    steps:
      - name: Checkout with ref ${{ github.sha }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18 # TODO
      - name: test
        shell: bash
        run: |
          npm install && npm run test
      - name: Merge PR for npm package-ecosystem
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          echo gh pr merge --auto --merge "$PR_URL"

  automerge_github_actions_pull_request:
    runs-on: ubuntu-latest
    needs:
      - fetch_metadata
    if: ${{ github.actor == 'dependabot[bot]' && needs.fetch_metadata.outputs.package-ecosystem == 'github_actions' }}
    steps:
      - name: Merge PR for github_actions package-ecosystem
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: echo gh pr merge --auto --merge "$PR_URL"
